### ISSUE TITLE
BUG: No Vendor Coordinator Panel? 

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#854] opened 2016-08-10 03:53 UTC
**This is a possible bug, but not an interrupt.  It's not a major issue right now**

I believe that I have both 'Vendor Reviewer' and 'Vendor Coordinator' status.  It looks that way when I check http://burlesque-expo.com/admin/auth/user/

My *reviewer* status seems to function.  When I go to http://burlesque-expo.com/vendor/reviewlist I see @bethlakshmi's test vendor ("Betty test").  When I click the 'review' link, I'm taken to the review page where I see the Reviewer tool (lower left-hand corner), but not the coordinator tool (which should be in the lower right corner).

**Comment by bethlakshmi** [comment] 2016-08-26 13:38
This is a duplicate of https://github.com/bethlakshmi/GBE2/issues/865

**Comment by burlexpo** [comment] 2016-08-26 23:33
So, really what you mean is #865 is a duplicate of this.... which one do we get rid of?

**Closed** 2016-08-26 23:33 UTC
Labels: bug, Estimation
