### ISSUE TITLE
download to performance music tries to link to /localhost?

### ISSUE THREAD

**Issue by eclecticmagpie** [bethlakshmi/GBE2#343] opened 2015-02-13 06:01 UTC
When I review tech info, I see a list of people and their music, as expected.  When I click on a tune name, I get a server not responding error, which says that it's trying to connect to localhost.  Am I doing something wrong, or is this a bug?

**Comment by burlexpo** [comment] 2015-02-13 13:00
@eclecticmagpie is right.  

For example, the HTML for "Lucy the Mooch" on http://gbeadmin.webfactional.com/reports/acttechinfo/view_summary/138  points to 
http://uploads/audio/Lucy_The_Mooch_short.mp3 and not to
http://gbeadmin.webfactional.com/uploads/audio/Lucy_The_Mooch_short.mp3 like it should.

Escalating and assigning to @bethlakshmi, but if @jonkiparsky can fix it faster, go for it.  This is a major blocker for Mike and David.

**Comment by burlexpo** [comment] 2015-02-13 13:02
@eclecticmagpie as a clunky workaround, the comment above shows what the real path should be for files and you can copy & paste to get at the files.  They're there.

**Comment by bethlakshmi** [comment] 2015-02-13 13:12
i just closed it on the live site.

**Comment by eclecticmagpie** [comment] 2015-02-13 13:49
Thank you!!

**Comment by eclecticmagpie** [comment] 2015-02-13 13:58
Some files work, and I get two different types of errors on some of the others. The Mooch, in particular, under Rhinestone, still doesn't work; Burlesque Majorette on the other hand does. 

I have not tested exhaustively; can do that later this afternoon or evening if helpful. Recent testing done on iPhone; not yet on computer. As far as I can tell, I'm on the live site.

If the workaround works (which I haven't yet tested but will later today) you can treat this as low or medium priority; even if it doesn't, it's not a problem for me till Tuesday at the earliest.

**Comment by jonkiparsky** [comment] 2015-02-14 05:52
Cannot reproduce for "the Mooch". @eclecticmagpie can you confirm that this issue is still live, and if so provide a reproducible test case.

**Comment by burlexpo** [comment] 2015-02-14 13:17
I think @bethlakshmi said (verbally, to me) that she fixed this and pushed a fix.  Betty, if so will you close this issue?

**Comment by bethlakshmi** [comment] 2015-02-14 17:03
I also said it in the comments in this thread that I fixed it.  
However, @eclecticmagpie is reporting a very different problem (some tracks work, some tracks don't) - which should be a separate bug if it's still active...

@eclecticmagpie  - I can't reproduce this on The Mooch. 

Some debugging/testing notes here:
 1 - this issue was for every single track on the site.  The problem was a poorly formatted link that resulted in no way to download the music.  That is permanently and completely fixed so I am closing this ticket.

 2- if you have a case where some tracks work and some tracks don't, we have something different and it should a separate ticket so this one doesn't get all kinds of confusing.

A note on the "some tracks work and some don't" type problem... if reporting, please report answers for:
- is it the same track every time?
- exactly what does it tell you when it fails?  A cut copy paste of a bunch of error stuff would be helpful.
- if attempting to load the track sometimes works and sometimes doesn't, we have a server load problem that will be hard for me to fix.

**Closed by bethlakshmi** 2015-02-14 17:03 UTC
Labels: High Priority

**Comment by eclecticmagpie** [comment] 2015-02-14 18:49
I will start some new tickets, with more detailed info. Some issues have been resolved, some have not, and I've done some more testing.
