### ISSUE TITLE
Fix master runcoverage problem

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#731] opened 2016-02-19 04:47 UTC
When I do run coverage in my vagrant, i get;

```
======================================================================
ERROR: tests.scheduler.test_volunteer_management.test_scheduled_volunteer_opportunity_shows_day
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/vagrant/expo/tests/scheduler/test_volunteer_management.py", line 57, in test_scheduled_volunteer_opportunity_shows_day
    response = edit_event(request, show_sevent.pk, event_type='Show')
  File "/vagrant/expo/scheduler/views.py", line 898, in edit_event
    return edit_event_display(request, item)
  File "/vagrant/expo/scheduler/views.py", line 966, in edit_event_display
    return render(request, template, context)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 85, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 85, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sekizai/templatetags/sekizai_tags.py", line 79, in render_tag
    rendered_contents = nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms/templatetags/cms_tags.py", line 670, in render_tag
    rendered_contents = nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 155, in render
    return self.render_template(self.template, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 137, in render_template
    output = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 85, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 203, in render
    nodelist.append(node.render(context))
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 897, in render
    return render_value_in_context(output, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 875, in render_value_in_context
    value = force_text(value)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/encoding.py", line 100, in force_text
    s = s.__unicode__()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 425, in __str__
    return self.as_widget()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 475, in as_widget
    return widget.render(name, self.value(), attrs=attrs)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/widgets.py", line 504, in render
    options = self.render_options(choices, [value])
  File "/usr/local/lib/python2.7/dist-packages/django/forms/widgets.py", line 535, in render_options
    output.append(self.render_option(selected_choices, option_value, option_label))
  File "/usr/local/lib/python2.7/dist-packages/django/forms/widgets.py", line 511, in render_option
    option_value = force_text(option_value)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/encoding.py", line 100, in force_text
    s = s.__unicode__()
  File "/vagrant/expo/scheduler/models.py", line 342, in __unicode__
    return unicode(self.describe)
  File "/vagrant/expo/scheduler/models.py", line 336, in describe
    resourceitem_id=self.resourceitem_id).name
  File "/usr/local/lib/python2.7/dist-packages/model_utils/managers.py", line 185, in get_subclass
    return self.get_queryset().get_subclass(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/model_utils/managers.py", line 160, in get_subclass
    return self.select_subclasses().get(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: LocationItem matching query does not exist.
```

i'm trying a vagrant re-provision now to see if a clean environment helps.
if not, i think I can work a fix.

**Comment by jonkiparsky** [comment] 2016-02-19 05:08
Duplicate of #696

**Comment by bethlakshmi** [comment] 2016-02-19 05:14
OK... found out something weird.  This breaks when my gbe_dev db is using a copy of the current live database.  But if i create a fresh new gbe_dev database, with syncdb and migrations, then it works fine.

@jonkiparsky - any clue how runcoverage testing operates differently from ./manage.py test - and how it connects to the mysql database?

**Comment by bethlakshmi** [comment] 2016-02-19 05:18
@jonkiparsky on #696 - do you get that problem when you do runcoverage?  And not when you do "./manage.py test" - I was concerned that since they are triggered by different causes they may actually be different.

**Comment by jonkiparsky** [comment] 2016-02-19 05:23
runcoverage is just this:
```alias runcoverage='cd /vagrant/expo;coverage run --source="." ./manage.py test tests -s;coverage html --omit="*/migrations/*,tests/*"'
```

I always just run the coverage (because I like to keep that up to date) so I haven't seen if there's any difference between using the alias and the canonical form, but I would be very surprised if there were.

**Comment by jonkiparsky** [comment] 2016-02-19 06:03
ran tests just now using the `./manage.py test tests` form, same problem.

**Comment by jonkiparsky** [comment] 2016-03-04 07:08
Got stuck on this one again. 
I've tracked it down into the form_table.tmpl -it's trying to get a LocationItem to describe() itself somewhere in there, and the LocationItem isn't cooperating. I'm wondering if it's a problem with the fixtures. (ie, if they're not in the database, then LocationItem.describe() will fail, maybe?)

**Comment by jonkiparsky** [comment] 2016-03-28 01:09
Closing this since it's a duplicate.

**Closed by jonkiparsky** 2016-03-28 01:09 UTC
Labels: Low Priority
