### ISSUE TITLE
No schedule display?

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#224] opened 2015-01-04 04:44 UTC
I don't know if this is a big or just that my primary persona doesn't have any schedule items.

In my personal pane (rightmost column) I can see that I'm in The Rhinestone Revue; shouldn't something related to that show up in my center column (schedule)? Currently, my center column is completely blank.

**Comment by jonkiparsky** [comment] 2015-01-04 05:39
It's because you have no allocations. I've made you a stage kitten, you should see that on your schedule.

**Comment by jonkiparsky** [comment] 2015-01-04 05:42
If there's a discrepancy between your right-column schedule and your center, let's reproduce it and fix it on a dev stack, not on live - vendors should be a mirror of live code (but not live data), so let's use that.

**Comment by jonkiparsky** [comment] 2015-01-04 06:29
Closing this, since schedule display is there on live site.

**Closed by jonkiparsky** 2015-01-04 06:29 UTC

**Comment by bethlakshmi** [comment] 2015-01-06 01:29
@burlexpo - When I originally set up the scheduling - it did a check to see
if the person was in an act that was in an show, and if that was true, the
show would show up on the schedule.  If, however, the person was the
*contact* for the show, but not a performer in the show, the show did NOT
show up on the schedule (for example, if Frankie fills out the form for
Michelle, and names Michelle as the soloist, then Frankie has the "bid" as
the contact, but Michelle is the performer and it shows up on her schedule).

We should verify that if we haven't already.
