### ISSUE TITLE
BUG: Rehearsal slots are screwed up URGENT

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#1208] opened 2017-12-31 16:07 UTC
Because I'm getting a notification saying I need to schedule myself for a rehearsal (as MC of The Main Event), I opened my tech info and got a message saying "We have no rehearsal slots currently available. Please contact us if you have not yet signed up for a rehearsal slot and wish to."

And I thought "That can't be so", so I visited http://gbelive.webfactional.com/scheduler/list/GenericEvent and looked at the summary for "ME-Rehearsal" 

The 3pm-4pm timeslot has a max of 9 volunteers -- and has 14 acts assigned to it.
The 4pm-5pm timeslot has a max of 9 volunteers -- and has 1 act assigned to it.
The 5pm-6pm timeslot has a max of 9 volunteers -- and has 6 acts assigned to it.
The 6pm-7pm timeslot has a max of 9 volunteers -- and has zero acts assigned to it.

I should be able to sign up for any time slot except 3pm to 4pm.
3pm - 4pm has 5 too many acts in it.

We need to:
- fix things so people can sign up for open timeslots.
- fix things so once a timeslot is full people cannot sign up for it
- and I need to manage things to move people from 3pm-4pm to some other timeslot, but I can't do that until the first two fixes are in place.

**Comment by bethlakshmi** [comment] 2017-12-31 16:58
OK, first set of notes:

- the Main Event Rehearsal is fucked up - I don't know (yet) how anyone ever managed to register - it's a "Volunteer Opportunity" instead of a "Rehearsal Slot", and so it doesn't appear in the act tech info form.  
     - solution - I just fixed that manually on live and the 4:00 and 5:00 rehearsals now show up.
- " The 6pm-7pm timeslot has a max of 9 volunteers -- and has zero acts assigned to it." - where are you getting that info?  I see three rehearsal slots here:
       http://www.burlesque-expo.com/scheduler/list/GenericEvent
      - question:  can you point me to the 6-7 PM slot??
- the high number of acts is due to double counting - I have 9 unique acts, which have been booked a collective total of 14 times.  I haven't figured out WHY yet.
      - solution - I can manually clean this up, I don't think we need to ask anyone to change their slot.  But I want to figure out the root cause first.

Weirdness:
- I can't explain how the ME Rehearsal became a volunteer opportunity.  My DB records show it has been since at least 12-14-17, but if it was ALWAYS a volunteer opportunity, how could these acts possibly get signed up?  If it changed, who or what changed it?  I can't think of any code in the system that would change the event type.

**Comment by bethlakshmi** [comment] 2018-01-01 22:23
From further research, the duplicate actions occurred as a series, with one exception.  They were a weird burst of sequential ids, but there's no clue what triggered it.  The DB dump is my 12-31 copy.

I manually cleaned up the data, but I'm not happy at not having a root cause.

The thing I feel relatively sure of is - it wasn't user triggered.  It's unlikely that all the users would stumble over a bug and create this pattern of data.  It's more likely that a special privilege person triggered something with unexpected consequences.

**Comment by bethlakshmi** [comment] 2018-04-06 03:02
Unhappily closing because I can't see what else to do.  We now have a rehearsal slot editor, so it will be a bit easier to watch this and see if something goes astray.

**Closed by bethlakshmi** 2018-04-06 03:02 UTC
Labels: Needs Root Cause, bug
