### ISSUE TITLE
Downloading Act Tech Reports Gives 500 Error

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#993] opened 2017-02-08 04:23 UTC
From @eclecticmagpie 

I logged in to the site.
I pulled down the Special menu.
I selected "Report"
I clicked on "Act Tech Info"
It defaulted to "GBE 2017"
I selected "Main Event"

Information for the Main Event appeared, with 2017 dates listed.
I clicked on  "All Details" 
I received the 500 error.  

The error only occurs on Main Event and Rhinestone Revue, and only on attempting to download the CSV file.

**Comment by bethlakshmi** [comment] 2017-02-08 18:40
Duplicate of https://github.com/bethlakshmi/GBE2/issues/990

Currently being reviewed by @gawaineo - hoping to get this and audio onto site tomorrow.

**Closed by bethlakshmi** 2017-02-08 18:40 UTC
Labels: bug, High Priority
