### ISSUE TITLE
Volunteers assigned via the event page don't seem to show up on reports

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#687] opened 2016-01-30 03:57 UTC
I'm reasoning from the general to the specific here, but...

I went to http://burlesque-expo.com/scheduler/edit/Show/1328 and created a series of volunteer positions, including "The Bordello - MC".  I used the "Staff" button to add Sailor St. Claire to the role.  That seems to have worked (http://burlesque-expo.com/scheduler/edit/GenericEvent/2102 -- scroll down to the bottom; there she is).

However, if I look at the show staffing report of The Bordello (http://burlesque-expo.com/reports/staff_area/367) while several other volunteers show up, and the volunteer _position_ ""The Bordello - MC" shows up, it shows up with no one assigned to it.

The volunteers who do appear (Board Op, Playback, Kitten) were all assigned through the **Review Volunteers** functionality.

This is a serious problem because it means that all volunteers have to be assigned through the _Assign_ function on http://burlesque-expo.com/volunteer/reviewlist which means I only have access to people who have filled out a volunteer bid (which is less than half of our volunteer staff...)

[Commenting in @jonkiparsky because I don't remember who the author of which piece of code was]

**Comment by bethlakshmi** [comment] 2016-01-30 06:22
yep... I see it.  It's taking a back seat to the 500 error and the 500 error fix doesn't fix it... (just testing 500 error with most live data I can get)

**Comment by jonkiparsky** [comment] 2016-01-30 06:24
I can look at this while Betty gets a fix together for the 500

**Comment by bethlakshmi** [comment] 2016-01-30 06:58
I'm willing to leave @jonkiparsky to this one... if it's inscruitable, I'll chime in in the morning.
But time for bed and ibuprofen.

**Comment by jonkiparsky** [comment] 2016-01-30 07:31
Found it. Sailor was allocated as a "Performer". Changed to "Volunteer" and she shows up on the staff schedule. Need to clear up some confusion about the design here. The report says "staff schedules" but the internal code is all about "volunteers". I don't know which we're supposed to be getting.

**Comment by jonkiparsky** [comment] 2016-01-30 18:47
@burlexpo Can you advise? Is the as-built behavior correct, or do you want the report to include "Performers" as well? (and what about other roles??)

**Comment by burlexpo** [comment] 2016-01-31 06:23
I'm trying to figure out how to phrase this as to not increase the amount of chaos ;-)

I think that anyone assigned to a show or any event, really) through the Volunteer scheduling mechanism, regardless of the role they are labeled,  should show up when someone looks at the report for that event.  

It's counter-intuitive (to me, anyway) that somehow giving more information on a volunteer's role by using the *Volunteer Type* dropdown menu could somehow make a volunteer not appear in a report of the show for which he was scheduled....

**Comment by bethlakshmi** [comment] 2016-01-31 18:15
We use "Performer" roles in a number of special ways - the initial case was that a performer is a person who is performing an act in a show.  I get that the MC is also a performer, but the reports when I created them were very specifically for back stage help - which would have all been volunteers.  Such all the people on tech crew for a show... not for the performers.

We're down to I think two options:
- 1 - constrain volunteer type dropdown menu to make sure that volunteers are always of a volunteer type (eliminating "Performer" as an option)

- 2 - redesign what the report displays - WARNING - if you say you want to see performers, then I will start to wonder if you want all the different types of performers - for example the various acts that are cast in the show.  We could filter by "folks involved in a volunteer opportunity connected to this area" - ie, don't limit by role (what we currently do), limit by the type of child event.  That may not be crazy, but it's not at all what I wrote for last year.

**Comment by bethlakshmi** [comment] 2016-07-02 14:21
Moved to Low because Scratch and I couldn't figure out how to reproduce it.  But we have no record of it being fixed, in fact we have every reason to believe that it ended with a question and not a fix.

IMO it's worth a delay until we do more event scheduling work.

**Comment by bethlakshmi** [comment] 2016-12-26 04:08
I suspect this was fixed with caching.

If not, when the issue returns, I need a single concise writeup  - this ticket is now a very long tail.

**Closed by bethlakshmi** 2016-12-26 04:08 UTC
Labels: bug, Low Priority
