### ISSUE TITLE
Make it possible to drop an event from schedule

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#157] opened 2014-11-15 01:16 UTC
We want to drop any type of event (currently Shows, Classes, Generic Events) from the schedule.

The goal is to keep the data but in inactive status (not showing on any public way - not on grid, not on any list of active events).

**Comment by jonkiparsky** [comment] 2015-01-23 03:32
Duplicate of #245

**Closed** 2015-01-23 03:35 UTC
