### ISSUE TITLE
Replace all existing user names with related email address

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#1000] opened 2017-03-05 03:50 UTC
Internet standards have evolved.  Most site simply use the user's email address as their user name.  We should be proactive and fix this:

1) Replace all user names in DB with related email addresses
2) Send an email to all users telling them what happened

** This should be done after the mail queue problem is fixed because no one is going to remember their freaking password.

**Comment by bethlakshmi** [comment] 2017-08-04 13:28
Duplicate of #1090

**Closed by bethlakshmi** 2017-08-04 13:28 UTC
